version: '3'

services:
  http2ss:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: http2ss
    restart: unless-stopped
    ports:
      # HTTP proxy port (works for both HTTP and HTTPS traffic)
      - "8080:8080"
      # Shadowsocks SOCKS5 proxy port
      - "1080:1080"
    environment:
      - SS_SERVER=your_ss_server_ip
      - SS_PORT=8388
      - SS_PASSWORD=your_password
      - SS_METHOD=aes-256-gcm
    volumes:
      - ./logs:/var/log