version: '3'

services:
  http2ss:
    # image: ghcr.io/zweily/http2ss:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: http2ss
    restart: unless-stopped
    ports:
      # HTTP proxy port (works for both HTTP and HTTPS traffic)
      - "8080:8080"
      # Shadowsocks SOCKS5 proxy port
      - "1080:1080"
    # Remove single-server environment variables
    # environment:
    #   - SS_SERVER=66.187.4.229
    #   - SS_PORT=15430
    #   - SS_PASSWORD=S0nicwa11
    #   - SS_METHOD=aes-256-gcm
    volumes:
      - ./logs:/var/log
      - ./config/ss_servers.json:/config/ss_servers.json:ro